nss-day-cohort-44/rare-rowdy-lobsters

- src/components/ApplicationViews.js
- src/components/categories/CategoryForm.js
- src/components/categories/CategoryList.js
- src/components/categories/CategoryProvider.js
New feature
To test:
`npm start`
Open `http://localhost:3000/categories`
Try to add a new category
> List categories and create new one

- src/components/auth/Register.js
- src/components/utils/HumanDate.js
The object collected from the register form now reflects the required fields on the server.
1. `git checkout wb-register`
1. Select `Not a member yet?`
1. Fill out the form and select `Register`
1. The page will not change but do a GET in Postman to ensure the user was added
> Client Side Register Form

- src/components/ApplicationViews.js
- src/components/nav/NavBar.js
- src/components/posts/PostList.js
The user should now be able to view posts made by any user.
- [ x] New feature (non-breaking change which adds functionality)
1. `git checkout mc-viewAllPosts`
1. `Once logged in, navigate to the All Posts page and verify that all posts are visible`
> Mc view all posts

- src/components/ApplicationViews.js
- src/components/posts/PostForm.js
- src/components/posts/PostList.js
- src/components/posts/PostProvider.js
creating posts fully works
- [ X] New feature (non-breaking change which adds functionality)
1. `git checkout dw-creatingPosts`
1. try adding a post
> Dw create posts

- src/components/posts/PostList.js
Reversed the list of posts in post list component so that most recent posts appear at the top.
- [x ] Bug fix (non-breaking change which fixes an issue)
1. `git checkout mc-recentFirst`
1. `In the browser, create a new post and verify that it goes to the top of the page for both my posts and all posts`
> Most recent first

- package-lock.json
- package.json
- src/components/ApplicationViews.js
- src/components/posts/PostDetail.js
- src/components/posts/PostProvider.js
Post details. Title, date, content, author displayed with logic to conditionally render an image if it exists. Trash and settings icons are imported but do not have functionality yet.
1. `git checkout wb-post-details`
1. Open http://localhost:3000
1. Select a post title to view post details
> Wb post details

- src/components/categories/CategoryList.js
- src/components/categories/CategoryProvider.js
1. `git checkout dk-delete-category`
1. `http://localhost:3000/categories` and click delete button
> Added delete button and functionality

- src/components/posts/PostDetail.js
- src/components/tags/TagPost.js
- src/components/tags/TagProvider.js
1. `git checkout dk-post-details-tags`
1. Create a new post and add tags to it
> Tags show up on post details

- src/components/posts/PostDetail.js
- src/components/tags/TagPost.js
- src/components/tags/TagProvider.js
.
1. `git checkout dk-delete-tags`
1. View post details, add and delete tags
> Authors can delete tags from their posts

- package-lock.json
- package.json
- src/components/ApplicationViews.js
- src/components/comments/CommentForm.js
- src/components/comments/CommentList.js
- src/components/comments/CommentProvider.js
- src/components/posts/Post.js
- src/components/posts/PostDetail.js
A user should now be able to add a comment to a post.
- [x ] New feature (non-breaking change which adds functionality)
1. `git checkout mc-createComments`
1. `navigate to the post detail page of any post`
1. `Click the comment icon`
1. `Type a comment and submit`
1. `You should be redirected to the post detail page. Go to postman, run a get request to http://localhost:8088 and verify that your new comment has been saved.`
> Mc create comments

- src/components/ApplicationViews.js
- src/components/comments/Comment.js
- src/components/comments/CommentList.js
- src/components/posts/PostDetail.js
You can now view comments associated with a post
- [x ] New feature (non-breaking change which adds functionality)
1. `git checkout mc-displayComments`
1. `In the browser, navigate to the post detail page, then click view comments. Verify that the associated comments are visible`
> Mc display comments

- src/components/ApplicationViews.js
- src/components/posts/PostDetail.js
- src/components/posts/PostForm.js
- src/components/posts/PostProvider.js
the edit feature works
1. `git checkout dw-editPost`
1. click on the details of a post, edit it and be sure to re-select the category. see if it edits
> Dw edit posts

- src/components/posts/PostForm.js
You can refresh on an edit page
- [ X] Bug fix (non-breaking change which fixes an issue)
1. `git checkout dw-editPost-bug`
1. go to a post detail, click the cog edit button. Then click refresh. If it doesn't break then it works.
> you can refresh on an edit page

- src/components/posts/Post.js
the author's name and category display with the posts
1. `git checkout dw-display-correctly`
1.look at your post list and see if they display the author's name and category
> the posts module now displays the authors name and category

- src/components/comments/CommentList.js
- src/components/comments/CommentProvider.js
1. `git checkout dk-delete-comment`
1. View a post's comments and click the trash can next to one
> Can delete comments from posts

- src/components/ApplicationViews.js
- src/components/comments/Comment.js
- src/components/comments/CommentForm.js
- src/components/comments/CommentProvider.js
You can now edit comments on a post.
1. `git checkout mc-editComments`
1. `Go to the view all comments section of a post, click the edit icon, and verify that you are presented with the comment form, prefilled with the information on the comment. Try to change the comment, save edit, then verify that it was changed.`
> Mc edit comments

- src/components/auth/Login.js
- src/components/comments/Comment.js
- src/components/comments/CommentList.js
Refactored to use onClick instead of Link for changing to comment edit form
1. `git checkout mc-onClickState`
1. `verify that you can still edit comments`
> Mc on click state

- src/components/ApplicationViews.js
- src/components/tags/TagForm.js
- src/components/tags/TagList.js
- src/components/tags/TagProvider.js
1. `git checkout dk-edit-tags`
1. Click the edit button next to a tag in tag list and change the label
> Able to edit tags

- src/components/ApplicationViews.js
- src/components/posts/PostDetail.js
- src/components/posts/PostForm.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
1. `git checkout branch-name`
1. `serve`
> Mc refactor

- src/components/posts/PostList.js
- src/components/posts/PostProvider.js
- src/components/posts/PostSearch.js
Post titles are searchable on MyPosts and AllPosts tabs
1. `git checkout jk-search`
1. `serve, search by string in AllPosts tab to see a title`
> search-posts working and posts still list in descending order

- src/components/posts/PostList.js
On both my posts and all posts, there is a dropdown menu which allows users to sort posts by category.
- [x ] New feature (non-breaking change which adds functionality)
1. `git checkout mc-sortPostsByCat`
1. `navigate to my posts, and select categories with the dropdown. Verify that the visible posts all have the desired category. Do the same on all posts page.`
> added a dropdown menu that sorts posts by category

- src/components/ApplicationViews.js
- src/components/Rare.js
- src/components/auth/Login.js
- src/components/nav/NavBar.js
- src/components/posts/Post.js
- src/components/posts/PostForm.js
- src/components/posts/PostList.js
- src/components/users/User.js
- src/components/users/UserList.js
- src/components/users/UserProvider.js
Admins now have a Users nav bar option, where they can view the names, usernames and account types of each user.
1. `git checkout wb-profile-list`
1. Create admins with the dummy data below  
1. Log in as an admin. `Users` should be an option in the nav bar.
1. Select the `Users` option to view the list of all users.
INSERT INTO Users ('first_name','last_name','email','bio','username','password','profile_image_url',"created_on","active","account_type_id") VALUES ('Coach', 'Steve', 'coach@aol.com', null, 'coach@aol.com', 'YES', null, 1611955074741, null, 1);
INSERT INTO Users …
> Users List

- src/components/posts/Post.js
- src/components/posts/PostForm.js
new features
-Posts made by admins are always approved. 
-posts made by authors do not start out as approved
-Under "view all posts", authors only see approved posts
- under "view all posts", admins see all posts and a button for approval. If they click "approve" then the posts becomes visible to all. 
- [X ] New feature (non-breaking change which adds functionality)
1) Delete all posts from all users before pulling down my branches
For front-end and back-end 
2. `git fetch --all`
3. `git checkout dw-approval-posts`
4. Sign in as an author
5. Create a post
**6. Make sure the …
> Dw approval post

- src/components/ApplicationViews.js
- src/components/Rare.js
- src/components/auth/Login.js
- src/components/nav/NavBar.js
- src/components/posts/Post.js
- src/components/posts/PostForm.js
- src/components/posts/PostList.js
- src/components/users/User.js
- src/components/users/UserDetail.js
- src/components/users/UserList.js
- src/components/users/UserProvider.js
The user details page is set up to display the user's first and last name, username, email, date the account was created and the account type.
1. `git checkout wb-user-details`
1. Log in as an admin.
1. Select the `Users` option from the nav bar
1. Select a users name
1. This should navigate you to the user details page where you can view the user's first and last name, username, email, date the account was created and the account type.
> User Details
